# Clippy linting configuration for harmony-agent

# Warn on all clippy lints
warn-on-all-wildcard-imports = true

# Cognitive complexity threshold
cognitive-complexity-threshold = 30

# Maximum function length
too-many-lines-threshold = 150

# Documentation
missing-docs-in-crate-items = true

# Avoid default trait access
avoid-breaking-exported-api = true
