# wg-agent Example Configuration
#
# This file demonstrates the TOML configuration format for wg-agent in standalone mode.
# It supports multiple named networks, each with their own WireGuard configuration.

# Default network configuration
[network.default]
# Enable WireGuard for this network
enable_wireguard = true

# WireGuard interface name (max 15 characters, alphanumeric with _ or -)
# Default: "wg0"
interface = "wg0"

# Maximum Transmission Unit (valid range: 1280-1500)
# Default: 1280
mtu = 1420

# Path to private key file (must be readable by agent, permissions 0600 recommended)
private_key_path = "/etc/wg-agent/private.key"

# DNS servers for this network (optional)
dns = ["10.100.0.2", "10.100.0.3"]

# Optional HTTP configuration (preserved from Harmony, not used by agent)
[network.default.http]
bind_address = "0.0.0.0"
bind_port = 8081

# WireGuard peers - can have multiple peers
[[network.default.peers]]
name = "runbeam-core"
# Base64-encoded public key (44 characters)
public_key = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOP=="
# Endpoint in format host:port
endpoint = "vpn.example.com:51820"
# Allowed IPs in CIDR notation
allowed_ips = ["10.42.0.0/16", "fd42:1::/48"]
# Persistent keepalive in seconds (0 to disable, or 10-300)
# Default: 25
persistent_keepalive_secs = 25

[[network.default.peers]]
name = "backup-peer"
public_key = "ZYXWVUTSRQPONMLKJIHGFEDCBAzyxwvutsrqponmlkjih=="
endpoint = "backup.example.com:51820"
allowed_ips = ["10.43.0.0/16"]
persistent_keepalive_secs = 30

# Production network configuration (separate network)
[network.production]
enable_wireguard = true
interface = "wg1"
mtu = 1280
private_key_path = "/etc/wg-agent/production.key"
dns = ["10.200.0.2"]

[[network.production.peers]]
name = "prod-gateway"
public_key = "1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefg=="
endpoint = "prod-vpn.example.com:51820"
allowed_ips = ["10.100.0.0/16", "172.16.0.0/12"]
persistent_keepalive_secs = 25

# Staging network configuration (minimal example)
[network.staging]
enable_wireguard = false  # Disabled by default
interface = "wg2"
private_key_path = "/etc/wg-agent/staging.key"

# Note: No peers defined for staging network yet
