[network.test]
enable_wireguard = true
interface = "wg99"
mtu = 1280
private_key_path = "/Users/xtfer/working/runbeam/wg-agent/tmp/test-config/test-private.key"
dns = ["1.1.1.1", "8.8.8.8"]

[[network.test.peers]]
name = "test-peer"
public_key = "TEST_PUBLIC_KEY_BASE64_ENCODED_AAAAAAAAAAAAAAAA="
endpoint = "127.0.0.1:51820"
allowed_ips = ["10.99.0.0/24"]
persistent_keepalive_secs = 25
